; PlatformIO Project Configuration File

[env:a-star32U4]
platform = atmelavr
board = a-star32U4
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/pololu/pololu-3pi-plus-32u4-arduino-library.git

[env:native]
platform = native
test_framework = googletest
test_build_src = true
build_src_filter = +<sort_coordinates.cpp> +<drive_distance.cpp>
